In [1]:
# This program use machine learning Decision Tree to predict if the stock price 
# will increase or decrease

In [2]:
pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.6/dist-packages (0.1.54)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.6/dist-packages (from yfinance) (0.0.9)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.6/dist-packages (from yfinance) (1.0.5)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.6/dist-packages (from yfinance) (1.18.5)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.6/dist-packages (from yfinance) (2.23.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24->yfinance) (2018.9)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24->yfinance) (2.8.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20->yfinance) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20->yfinance) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20->yfinance) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20->yfinance) (2020.6.20)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.6.1->pandas>=0.24->yfinance) (1.15.0)

In [3]:
#import the lib

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import yfinance as yf
import numpy as np
import pandas as pd

In [4]:
df = yf.download("AMD", start="2020-08-17", end="2020-09-17")
df

[*********************100%***********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close    Volume
Date
2020-08-17  82.089996  83.059998  81.550003  82.419998  82.419998  31450200
2020-08-18  82.800003  82.879997  81.029999  81.660004  81.660004  30970500
2020-08-19  81.779999  81.849998  80.449997  81.089996  81.089996  37507400
2020-08-20  79.739998  82.839996  79.120003  82.769997  82.769997  42948900
2020-08-21  83.290001  84.410004  82.230003  83.809998  83.809998  48280300
2020-08-24  84.550003  85.330002  82.550003  83.080002  83.080002  38036100
2020-08-25  83.360001  86.620003  82.349998  86.349998  86.349998  49234400
2020-08-26  86.970001  87.720001  85.199997  86.019997  86.019997  47157300
2020-08-27  86.349998  86.580002  82.940002  83.800003  83.800003  42194200
2020-08-28  84.300003  86.040001  84.190002  85.550003  85.550003  40723300
2020-08-31  85.050003  92.639999  85.050003  90.820000  90.820000  90655900
2020-09-01  91.919998  92.510002  90.190002  92.180000  92.180000  56117100
2020-09-02  94.010002  94.279999  88.739998  90.220001  90.220001  50366900
2020-09-03  87.839996  88.470001  81.589996  82.540001  82.540001  87462700
2020-09-04  81.449997  84.389999  76.330002  82.010002  82.010002  82267800
2020-09-08  78.050003  81.879997  78.000000  78.690002  78.690002  54955700
2020-09-09  81.400002  82.440002  79.279999  81.910004  81.910004  54163900
2020-09-10  83.070000  83.309998  78.379997  78.980003  78.980003  51499400
2020-09-11  79.820000  79.989998  75.040001  76.339996  76.339996  54763000
2020-09-14  76.800003  78.820000  76.260002  77.900002  77.900002  47448700
2020-09-15  77.660004  80.330002  75.970001  78.930000  78.930000  57874400
2020-09-16  79.349998  79.720001  76.540001  76.660004  76.660004  38393500

In [5]:
# Create target column
df['Price_Up'] = np.where(df['Close'].shift(-1)>df['Close'],1,0)
df

                 Open       High        Low  ...  Adj Close    Volume  Price_Up
Date                                         ...
2020-08-17  82.089996  83.059998  81.550003  ...  82.419998  31450200         0
2020-08-18  82.800003  82.879997  81.029999  ...  81.660004  30970500         0
2020-08-19  81.779999  81.849998  80.449997  ...  81.089996  37507400         1
2020-08-20  79.739998  82.839996  79.120003  ...  82.769997  42948900         1
2020-08-21  83.290001  84.410004  82.230003  ...  83.809998  48280300         0
2020-08-24  84.550003  85.330002  82.550003  ...  83.080002  38036100         1
2020-08-25  83.360001  86.620003  82.349998  ...  86.349998  49234400         0
2020-08-26  86.970001  87.720001  85.199997  ...  86.019997  47157300         0
2020-08-27  86.349998  86.580002  82.940002  ...  83.800003  42194200         1
2020-08-28  84.300003  86.040001  84.190002  ...  85.550003  40723300         1
2020-08-31  85.050003  92.639999  85.050003  ...  90.820000  90655900         1
2020-09-01  91.919998  92.510002  90.190002  ...  92.180000  56117100         0
2020-09-02  94.010002  94.279999  88.739998  ...  90.220001  50366900         0
2020-09-03  87.839996  88.470001  81.589996  ...  82.540001  87462700         0
2020-09-04  81.449997  84.389999  76.330002  ...  82.010002  82267800         0
2020-09-08  78.050003  81.879997  78.000000  ...  78.690002  54955700         1
2020-09-09  81.400002  82.440002  79.279999  ...  81.910004  54163900         0
2020-09-10  83.070000  83.309998  78.379997  ...  78.980003  51499400         0
2020-09-11  79.820000  79.989998  75.040001  ...  76.339996  54763000         1
2020-09-14  76.800003  78.820000  76.260002  ...  77.900002  47448700         1
2020-09-15  77.660004  80.330002  75.970001  ...  78.930000  57874400         0
2020-09-16  79.349998  79.720001  76.540001  ...  76.660004  38393500         0

[22 rows x 7 columns]

In [6]:
# Split the data set into a feature and target data set
X = df.iloc[:,0:df.shape[1]-1].values
Y = df.iloc[:,df.shape[1]-1].values

In [7]:
#Split data to 80% training and 20% testing data sets
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2)

In [8]:
#Create and train a module (DesicionTree)
tree = DecisionTreeClassifier().fit(X_train, Y_train)

#Show the model tested 
print(tree.score(X_test,Y_test))

0.4

In [9]:
#show the model predictions 
tree_predict = tree.predict(X_test)
print(tree_predict)

[0 0 0 0 1]

In [10]:
Y_test

array([1, 1, 0, 0, 0])